namespace CastleWindsor02.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;

    /// <summary>
    /// Event Entity.
    /// </summary>
    public class Events : EntityBase
    {
        /// <summary>
        /// Gets or sets the title.
        /// </summary>
        /// <value>The title.</value>
        public virtual string Title { get; set; }

        /// <summary>
        /// Gets or sets the where.
        /// </summary>
        /// <value>The where.</value>
        public virtual string Where { get; set; }

        /// <summary>
        /// Gets or sets the when.
        /// </summary>
        /// <value>The when.</value>
        public virtual DateTime When { get; set; }

        /// <summary>
        /// Gets or sets the description.
        /// </summary>
        /// <value>The description.</value>
        public virtual string Description { get; set; }

        /// <summary>
        /// Gets or sets the generated by.
        /// </summary>
        /// <value>The generated by.</value>
        public virtual UserInfo GeneratedBy { get; set; }
    }
}